# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  secret_key_base: 974796d03a2dbc18e710b1c53f6ff50faf3c36b13fcaa4fe7baf0f9120ea7c7e070c8566e8e0a612b3cdaeb65dc431a00be33426bad156da3bebfee621d22d94

test:
  secret_key_base: 0ad471f2d8ccf4705bdb2057ddb9a82518ff0f7d8dab1741fdc2b12836540bb573010c1ceceb8b0795dc6f20f920e0dd0aa7b07c0b86e098c93516cc987b9652

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
